### ISSUE TITLE
keyCode is deprecated

### ISSUE THREAD

**Issue by mu-2025** [yomotsu/hold-event#8]
KeyboardEvent.keyCode is deprecated now, could you please update it to code or key？
![image](https://user-images.githubusercontent.com/5102623/186570273-5441344e-bd60-4f9b-a221-e60fc6181a45.png)

**Comment by yomotsu** [comment]
Thanks for your suggestion.
I understand and will change it using `KeyboardEvent.code` suggested https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode.
It will be a breaking change tho.

**Comment by yomotsu** [comment]
@ASCII26 
Updated! now `KeyboardKeyHold` class takes `KeyboardEvent.code`.
e.g.
```js
const keyLeft = new holdEvent.KeyboardKeyHold( 'ArrowLeft' );
```
